kind: pipeline
name: default

steps:
  - name: test
    image: bluerain/policr:build
    pull: true
    commands:
      - shards --production
      - mkdir data
      - POLICR_ENV=test crystal sam.cr -- db:setup
      - POLICR_ENV=test crystal spec

  - name: build
    image: bluerain/policr:build
    pull: true
    commands:
      - shards build --release --progress --production --warnings=all

  - name: push-app-image
    image: plugins/docker
    settings:
      repo: bluerain/policr
      username: bluerain
      password:
        from_secret: docker_password
      dockerfile: Dockerfile
      tags: latest
    when:
      branch:
        - master
      event:
        - push

  - name: push-migration-image
    image: plugins/docker
    settings:
      repo: bluerain/policr
      username: bluerain
      password:
        from_secret: docker_password
      dockerfile: migration.Dockerfile
      tags: migration
    when:
      branch:
        - migration/update
      event:
        - push
